services:
  frontend:
    image: ghcr.io/qwerty55558/my-hospital-project:latest
    container_name: mhp-fe
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
